id: P010357
initial_creation_type: ocr
source_metadata:
  id: bdr:W23932
  title: ཡོངས་རྫོགས་བསྟན་པའི་ཉམས་ལེན་སྡོམ་པ་གསུམ་གཏན་ལ་འབེབས་པ་འཇམ་དབྱངས་བླ་མའི་དགོངས་རྒྱན
  author: ''
  volumes:
    12366a6fd4c34e42879ed9d8c5da33fd:
      image_group_id: I3555
      title: ''
      volume_number: 1
      total_pages: 208
