id: P010357
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 20:45:44.890163
source_metadata:
  id: bdr:W23932
  title: ཡོངས་རྫོགས་བསྟན་པའི་ཉམས་ལེན་སྡོམ་པ་གསུམ་གཏན་ལ་འབེབས་པ་འཇམ་དབྱངས་བླ་མའི་དགོངས་རྒྱན
  author: ''
  volumes:
    12366a6fd4c34e42879ed9d8c5da33fd:
      image_group_id: I3555
      title: ''
      volume_number: 1
      total_pages: 208
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
