id: I0EE54736
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:39:09+00:00'
last_modified: '2022-06-08T12:59:49.274554+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23932
  title: ཡོངས་རྫོགས་བསྟན་པའི་ཉམས་ལེན་སྡོམ་པ་གསུམ་གཏན་ལ་འབེབས་པ་འཇམ་དབྱངས་བླ་མའི་དགོངས་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    28DC:
      image_group_id: I3555
      title: ''
      total_pages: 208
      order: 1
      base_file: 28DC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
